name: rlbook
channels:
  - conda-forge
  - plotly
dependencies:
  # code
  - python 3.11.*
  - jax 0.4.*
  - equinox 0.11.*
  # visualization
  - bokeh
  - jupyter_bokeh
  - tqdm
  - latexify-py
  # book
  - jupyter-book
  - jupyterlab
  - jupytext 1.16.*
  - swig
  # github pages
  - ghp-import
  # pip
  - pip:
    - "gymnasium[box2d]"
    - sphinx-proof
