name: rlbook
channels:
  - conda-forge
  - plotly
dependencies:
  # code dependencies
  - python 3.11.*
  - jax 0.4.*
  - equinox 0.11.*
  # visualization dependencies
  - plotly
  - tqdm
  # book dependencies
  - jupyter-book
  - jupyterlab
  - jupytext 1.16.*
  - swig
  - ghp-import
  - pip:
    - "gymnasium[box2d]"
    - sphinx-proof
