name: rlbook
channels:
  - conda-forge
  - plotly
dependencies:
  - python 3.11.*
  - gymnasium 0.29.*
  - jax 0.4.*
  - jupyter-book
  - jupyterlab
  - plotly
  - jupytext 1.16.*
  - pip:
    - sphinx-proof
