[project]
name = "rlbook"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Alexander Cai", email = "alexandercai@outlook.com" }
]
requires-python = ">=3.11"
dependencies = []
