title : "CS/STAT 184: Introduction to Reinforcement Learning"
author: Alexander D. Cai
logo: 'qe-logo-large.png'

description: >-
  An undergraduate textbook on reinforcement learning from a primarily
  statistical perspective.

execute:
  execute_notebooks           : cache

only_build_toc_files          : true

html:
  home_page_in_navbar         : false

notebook_interface            : "notebook"

repository:
  url                         : https://github.com/adzcai/cs-stat-184-notes

binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"

bibtex_bibfiles:
  - references.bib

sphinx:
  config:
    bibtex_reference_style    : "author_year"
    mathjax_path              : "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
    mathjax3_config:
      tex:
        macros:
          "E"                 : "\\mathop{\\mathbb{E}}"
          "P"                 : "\\mathop{\\mathbb{P}}"

          # for flexibility with different conventions
          "hi"                : "h"
          "hor"               : "H"
          "st"                : "s"
          "act"               : "a"
  extra_extensions:
    - sphinx_proof

latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex
