title : "CS/STAT 184: Introduction to Reinforcement Learning"
author: Alexander D. Cai
logo: shared/184.png

description: >-
  An undergraduate textbook on reinforcement learning from a primarily
  statistical perspective.

execute:
  execute_notebooks           : cache

only_build_toc_files          : true

html:
  home_page_in_navbar         : false
  comments:
    utterances:
      repo: "adzcai/cs-stat-184-notes"

notebook_interface            : notebook

repository:
  url                         : https://github.com/adzcai/cs-stat-184-notes
  path_to_book                : book
  branch                      : main

binder:
  binderhub_url               : https://mybinder.org
  text                        : Launch binder

bibtex_bibfiles:
  - "shared/references.bib"

sphinx:
  config:
    # duplicate configuration for web and pdf
    latex_elements:
      pointsize               : 12pt
      preamble                : |
        \let\P\undefined
        \DeclareMathOperator*{\E}{\mathbb{E}}
        \DeclareMathOperator*{\P}{\mathbb{P}}
        \newcommand{\hi}{h}
        \newcommand{\hor}{H}
        \newcommand{\st}{s}
        \newcommand{\act}{a}
        \newcommand{\kl}[2]{\mathrm{KL}\left(#1 \parallel #2\right)}
    mathjax3_config:
      tex:
        macros:
          "E": "\\mathop{\\mathbb{E}}"
          "P": "\\mathop{\\mathbb{P}}"
          "hi": "h"
          "hor": "H"
          "st": "s"
          "act": "a"
          "kl": ["\\mathrm{KL}\\left(#1 \\parallel #2\\right)", 2]
    bibtex_reference_style    : "author_year"
    mathjax_path              : "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
  extra_extensions:
    - sphinx_proof

latex:
  latex_documents:
    targetname: book.tex
